"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.

Reference: https://stackoverflow.com/a/24483426

(a,b,c) this is (b+c, b+2*c, 2*b+3*c).

We only keep track of c as the even number in the fibonacci series.
"""

b, c = 1, 2
limit = 4000000
sum = 0

while c < limit:
    sum += c
    _intermediate = b + (c << 0x01)
    c = b + c + _intermediate
    b = _intermediate

print(sum)
